[phases.setup]
nixPkgs = [
  "php83",
  "php83Packages.composer",
  "nginx",
  "libmysqlclient",
  "nodejs_18",
  "npm-9_x"
]

[phases.build]
cmds = [
  "composer install --ignore-platform-reqs"
]

[phases.start]
cmd = "php -S 0.0.0.0:$PORT -t public"